### ISSUE TITLE
Subtitles on search results

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#26]
Replace collection and artist with date
<img width="1934" alt="Screenshot 2023-08-01 at 3 56 10 PM" src="https://github.com/lxcprojects/keywords/assets/59920290/ebf0100f-d035-4298-aace-ad7eabf16f61">

**Comment by jabrah** [comment]
Turns out we can't directly update this in templates, since the search results HTML is defined in the search-ui JS code. In the PR linked, I made a change to the JS to allow templates to specify which fields to show in the subheader of the results. This level of change isn't ideal from a compatibility standpoint with Wax/Wax-facets, but if desired, I can see about submitting that change to those repositories

**Comment by egpalazzolo** [comment]
Oh wow okay. That's pretty interesting that it's deep in the JS. Do you mean that you were already able to make the change in our templates and you could see if the Wax people wanted to add that flexibility to the platform, generally?

**Comment by jabrah** [comment]
The PR has the changes needed to update the search results in our site. Similar to other changes we've made (like with the gallery component) we might see if it should be pushed upstream to wax / wax-facets in the future
