### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#7]
Finally went in and added properly sized images (1140x) to get the simple derivatives. Now, trying to figure out how to get those to render instead of the json manifests (I've deleted the IIIF files from all of the folders). I think that the code for selecting which images to display on the keywords.html pages in the _layouts/generic_collection_item.html but after playing around a little with commenting out parts of the liquid code and even deleting the openseadragon folder under _site/js/openseadragon, still not figuring out how to get the .html files for the individual document pages to get rid of the code looking for a json manifest to supply the images. Would love some help figuring out how to get the new, simple formats to work!

**Comment by jabrah** [comment]
Looks like there's a few things going on here. One important aspect is that running the derivatives task doesn't update the individual pages for the documents (e.g. `_keywords/d0005.md`) which were initially generated by the `wax:pages` task.

You could either manually update these pages to match the `thumbnail` and `full` columns from the original CSV, or you could delete these pages and rerun the wax:pages task. Although, when I tested this, the wax:pages task resulted in slightly different data that may actually break facets -- I saw different delimiters (`;` instead of `|`)

I'm not 100% on switching over to the simple image viewer, as opposed to the OpenSeaDragon viewer, I'll leave another comment when I know more about that

**Comment by jabrah** [comment]
Simple image viewer can't show multi-page documents, so we'll stick with the IIIF.
